### ISSUE TITLE
the result is very poor

### ISSUE THREAD

**Issue by abner2015** [shamangary/SSR-Net#18]
it is amazing work, thank for u work. But the result is very poor except for gender . how can i improve the model

**Comment by shamangary** [comment]
Hello. Considering the original project of SSR-Net is meant to be age estimation instead of gender estimation, it is not considered as the target here. However, there are some potential issues of gender estimation. The labels of gender estimation do not include the gray area (ex: a guy looks like a girl or vice versa), it is not enough for training the gender as a regression problem for now. I would suggest that using classification technique for gender until any further datasets can be used in this problem.
