### ISSUE TITLE
Could you please tell me what does 'lambda-local' and 'lambda_d' mean in 'SSR_net'? Thank you!

### ISSUE THREAD

**Issue by Leon-Zijie-Li** [shamangary/SSR-Net#28]
Thank you for providing such an extrodinary image-processing solution, and I have already run the code and read the paper related to this project.

I have a question about parameters 'lambda_d' and 'lambda_local'. I can't understand their function and meaning. ( I noticed that you set them both as 1.0 in your demo).

**Comment by shamangary** [comment]
Hello @Leon-Zijie-Li,

Thank you for your appreciation. lambda_d and lambda_local are the hyper-parameter for tuning the dynamic scaling and dynamic index shifting respectively corresponding to Eq.(4) and Eq.(6). I did not write them down in the paper because they would make it more complex. Normally you don't have to tune them and that's why I set them to 1.
