### ISSUE TITLE
Accuracy question about gender estimation

### ISSUE THREAD

**Issue by mayidu** [shamangary/SSR-Net#7]
hello, I use SSR-Net to estimate gender with wiki pre-model, but the value obtained does not seem to be a confidence， the values of males are greater than 1, and the values of females is not less than 0.5, mostly is 0.9999.... , so there are many errors with 0.5 as threshold.
Is there a problem with my test?
Thank you!

**Comment by shamangary** [comment]
Hello. In the real-world experiment, we found that SSR-Net for gender recognition may only detect long hair for determining the gender. Therefore a girl with short hair may also be recognized as a male. 

This is caused by the dataset and the cropped range in face detection level. For example, we choose 40% wider region among the face detection region. It is suggested by the previous "age estimation" method. However, you could rebuild the dataset by setting the extra range smaller (or even smaller than the original face detected region) to avoid the hair interference. Or you may simply change a dataset which contains more short hair females.

**Comment by mayidu** [comment]
I understand, thank you very much and look forward to your retraining gender model.
